fix: fix incompatible byte -> CommandPermission conversion in Command
this fixes build error:
/build/waterdogpe/src/main/java/dev/waterdog/waterdogpe/command/Command.java:[100,17] incompatible types: byte cannot be converted to org.cloudburstmc.protocol.bedrock.data.command.CommandPermission